name: Simple docker compose deploy

on:
  workflow_call:

concurrency:
  group: production-deploy
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy ${{ github.event.repository.name }}
    runs-on: self-hosted

    steps:
      - name: Set app directory
        run: echo "APP_DIR=$HOME/${{ github.event.repository.name }}" >> "$GITHUB_ENV"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create deploy symlink
        run: |
          set -euo pipefail

          ln -sfn "$GITHUB_WORKSPACE" "$APP_DIR"

      - name: Decrypt secrets
        run: |
          set -euo pipefail

          cd "$APP_DIR"
          for encrypted_file in env/prod/.env*.enc; do
            decrypted_file="${encrypted_file%.enc}"

            echo "Decrypting: $encrypted_file"

            sops --decrypt "$encrypted_file" > "$decrypted_file"
            chmod 600 "$decrypted_file"
          done

      - name: Deploy
        run: |
          set -euo pipefail

          cd "$APP_DIR"
          echo "PERFECT!!!!"
          # docker compose up -d --build --remove-orphans

      - name: Cleanup
        if: always()
        run: |
          if [ -d "$APP_DIR" ]; then
            cd "$APP_DIR"
            docker image prune -f
          fi
